package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/cviecco/sss-distrib/lib/sssdoc"
	"github.com/stretchr/testify/require"
)

func TestGenerateAgeKeyCommand(t *testing.T) {
	tempDir := t.TempDir()
	outfile := filepath.Join(tempDir, "outfile")
	command := GenNewEncAgeKey{
		OutputPath: outfile,
		passphrase: "12345",
	}
	context := Context{}
	err := command.Run(&context)
	require.NoError(t, err)

}

// Generated by claude (sonnet 5)
func TestGenDocCmdRun(t *testing.T) {
	tempDir := t.TempDir()
	context := Context{}

	// Generate a couple of age keys so we have public key files to feed
	// into GenDocCmd.
	var pubKeyPaths []string
	for i := 0; i < 2; i++ {
		keyPath := filepath.Join(tempDir, fmt.Sprintf("age%d", i+1))
		genCommand := GenNewEncAgeKey{
			OutputPath: keyPath,
			passphrase: "12345",
		}
		err := genCommand.Run(&context)
		require.NoError(t, err)
		pubKeyPaths = append(pubKeyPaths, keyPath+".pub")
	}

	outputPath := filepath.Join(tempDir, "doc.json")
	genDocCommand := GenDocCmd{
		NumReqiredKeys: 2,
		OutputPath:     outputPath,
		PublicKeyPaths: pubKeyPaths,
	}
	err := genDocCommand.Run(&context)
	require.NoError(t, err)

	outputBytes, err := os.ReadFile(outputPath)
	require.NoError(t, err)

	var shareDoc sssdoc.ShareDoc
	err = json.Unmarshal(outputBytes, &shareDoc)
	require.NoError(t, err)
	require.Equal(t, 2, shareDoc.RequiredShares)
	require.Equal(t, len(pubKeyPaths), len(shareDoc.Shares))
}
