package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/cviecco/sss-distrib/lib/sssdoc"
	"github.com/stretchr/testify/require"
)

func TestGenerateAgeKeyCommand(t *testing.T) {
	tempDir := t.TempDir()
	outfile := filepath.Join(tempDir, "outfile")
	command := GenNewEncAgeKey{
		OutputPath: outfile,
		passphrase: "12345",
	}
	cmdContext := Context{}
	err := command.Run(&cmdContext)
	require.NoError(t, err)

}

// Generated by claude (sonnet 5)
func TestGenDocCmdRun(t *testing.T) {
	tempDir := t.TempDir()
	cmdContext := Context{}

	// Generate a couple of age keys so we have public key files to feed
	// into GenDocCmd.
	var pubKeyPaths []string
	for i := 0; i < 2; i++ {
		keyPath := filepath.Join(tempDir, fmt.Sprintf("age%d", i+1))
		genCommand := GenNewEncAgeKey{
			OutputPath: keyPath,
			passphrase: "12345",
		}
		err := genCommand.Run(&cmdContext)
		require.NoError(t, err)
		pubKeyPaths = append(pubKeyPaths, keyPath+".pub")
	}

	outputPath := filepath.Join(tempDir, "doc.json")
	genDocCommand := GenDocCmd{
		NumReqiredKeys: 2,
		OutputPath:     outputPath,
		PublicKeyPaths: pubKeyPaths,
	}
	err := genDocCommand.Run(&cmdContext)
	require.NoError(t, err)

	outputBytes, err := os.ReadFile(outputPath)
	require.NoError(t, err)

	var shareDoc sssdoc.ShareDoc
	err = json.Unmarshal(outputBytes, &shareDoc)
	require.NoError(t, err)
	require.Equal(t, 2, shareDoc.RequiredShares)
	require.Equal(t, len(pubKeyPaths), len(shareDoc.Shares))
}

func TestServerClient(t *testing.T) {

	// a serialized doc in a file

	tempDir := t.TempDir()
	cmdContext := Context{
		Debug: true,
	}

	// Generate a couple of age keys so we have public key files to feed
	// into GenDocCmd.
	var pubKeyPaths []string
	var privkeyPaths []string
	for i := 0; i < 2; i++ {
		keyPath := filepath.Join(tempDir, fmt.Sprintf("age%d", i+1))
		genCommand := GenNewEncAgeKey{
			OutputPath: keyPath,
			passphrase: "12345",
		}
		err := genCommand.Run(&cmdContext)
		require.NoError(t, err)
		pubKeyPaths = append(pubKeyPaths, keyPath+".pub")
		privkeyPaths = append(privkeyPaths, keyPath)
	}

	outputPath := filepath.Join(tempDir, "doc.json")
	genDocCommand := GenDocCmd{
		NumReqiredKeys: 2,
		OutputPath:     outputPath,
		PublicKeyPaths: pubKeyPaths,
	}
	err := genDocCommand.Run(&cmdContext)
	require.NoError(t, err)

	// Start the
	const serverport = 41414
	servercmd := ServerDemoCmd{
		ListenPort: serverport,
		DocPath:    outputPath,
	}
	c1 := make(chan error, 1)
	go func() {
		err := servercmd.Run(&cmdContext)
		c1 <- err
	}()

	//check for  http.ErrServerClosed
	select {
	case runerr := <-c1:
		require.NoError(t, runerr)
	case <-time.After(300 * time.Millisecond):
		t.Logf("seems server started correctly")
		//ctx1 := context.Background()
		//err = servercmd.server.Shutdown(ctx1)
		//require.NoError(t, err)
	}
	t.Logf("starting client then")
	//Now we start the client
	client := ClientCmd{
		KeyPath:    privkeyPaths[0],
		ServerURL:  fmt.Sprintf("http://127.0.0.1:%d", serverport),
		passphrase: "12345",
	}
	err = client.Run(&cmdContext)
	require.NoError(t, err)

	// shutdown actual server?
	time.Sleep(100 * time.Millisecond)
	ctx1 := context.Background()
	err = servercmd.server.Shutdown(ctx1)
	require.NoError(t, err)
}
